### ISSUE TITLE
Require that each executeOrder transaction is checked

### ISSUE THREAD

**Issue by NicoSantangelo** [decentraland/marketplace-contracts#19]
### Require that each executeOrder transaction is checked for Estate or Land rather than assuming one or the other based on the called function

A user with an Estate can put the Estate up for sale and subsequently remove all of the land in this estate prior to the execution of the sale. If a buyer then calls executeOrder()​ on this ​assetId​ (as opposed to ​safeExecuteOrder()​), they will be able to purchase this empty Estate

![image](https://user-images.githubusercontent.com/692077/46343604-a39c4680-c63e-11e8-93c7-0265818d5466.png)

----

@abarmat @nachomazzara I think this is a valid concern, but I can't remember if we did it on purpose or not. With their recommendation, we can have only one `executeOrder` function

**Comment by abarmat** [comment]
I’m in favor of having one executeOrder as it’s a cleaner interface, but in
the case that there is no fingerprint validation should we send an empty
string for that parameter?

**Comment by nachomazzara** [comment]
I think what they are trying to says is to check if the nft implements the get fingerprint interface so, if they call executeOrder instead of safeExecuteOrder fail cause it is an nft which should be buyed safetely
