### ISSUE TITLE
Collisions are possible with EstateRegistry’s getFingerprint()

### ISSUE THREAD

**Issue by NicoSantangelo** [decentraland/marketplace-contracts#20]
### Collisions are possible with EstateRegistry’s getFingerprint()

EstateRegistry.sol#L198​ ​- It’s possible to create colliding fingerprints with different estates and land compositions. This is due to the fact that   ’s and ​landId​’s can be identical

Consider adding the string “estateId” as a parameter to the the `abi.encodePacked()` function on ​this line​. No collisions will be possible with the new `getFingerprint()` function.

![image](https://user-images.githubusercontent.com/692077/46343775-2e7d4100-c63f-11e8-979b-4712948b81e0.png)

**Comment by eordano** [comment]
Yes!

**Comment by eordano** [comment]
Ready for review: https://github.com/decentraland/land/pull/108/files
