### ISSUE TITLE
Require that the NFT being sold or bought is an approved token

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/marketplace-contracts#22]
### Require that the NFT being sold or bought is an approved token

Consider creating a whitelist of approved NFTs that can be transacted in the marketplace.
Users can list any NFT for sale and users may be fooled into interacting with malicious NFT implementations. Adding a whitelist of approved NFTs will protect users from this set of attacks.

---

@abarmat @nachomazzara I think we talked about this before, but it's worth re-thinking. Should we do this?

**Comment by abarmat** [comment]
We can add checks for this in next iteration as of today they will interact
only in our front end which will set the nft address.

In the meantime we can monitor through events if someone published a
different nft address, but it will be a user using the contract by hand.

Let’s add this on a next upgrade, what do you think?
