### ISSUE TITLE
Put ERC721 token on escrow while listed.

### ISSUE THREAD

**Issue by chentschel** [decentraland/marketplace-contracts#4]
When creating a new sale order the contract checks it's authorized by the DAR of the ERC721 token in case of a successful sale.

`require(nonFungibleRegistry.isAuthorized(address(this), assetId));`

If we don't issue a transfer and put this item on "custody" by this marketplace, it could happen that when someones tries to execute the sale order and acquire the collectible, this contract wont be able to transfer it.

- Seller approves marketplace to transfer the ERC721 token.
- Seller creates a new sale order for the ERC721 token. 
- Seller cancels approval for this marketplace. (item is still listed)
- User tries to execute the sale order and acquire the item. -> FAIL

@eordano A proposal to overcome this situation is to put the item on escrow in this contract, until the sale order gets executed or canceled. In case it gets canceled, the ERC721 token should return its ownership to the original seller.

**Comment by eordano** [comment]
NACK; this causes too many troubles for dApps checking what are your current assets (you have to do more than one query for current parcels)
