### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mudgen** [decentraland/marketplace-contracts#50]
Hello,
Is it possible to change the license of this repo to MIT?  It would make it easier and clearer to integrate it into my contracts. 
Adding a marketplace for Aavegotchi. https://github.com/aavegotchi/aavegotchi-contracts

**Comment by eordano** [comment]
Hi there! Unfortunately, we prefer the Apache 2.0 license for two reasons:
* It explicitly grants you usage of any patents the original copyright owner has (AFAIK the contributors to this repo have not filled any patent claims, but if they had, you are free to use them)
* It is generally better understood by lawyers than the MIT license and seen as lower risk.

You can see some of the benefits of this license in this blogpost: https://opensource.com/article/18/2/how-make-sense-apache-2-patent-license
