### ISSUE TITLE
Legacy stuff

### ISSUE THREAD

**Issue by mudgen** [decentraland/marketplace-contracts#51]
Should I get rid of the legacy stuff in a new implementation of the marketplace contracts?    How does the legacy stuff fit in?

Example:
```Solidity
    // [LEGACY] Auction events
    event AuctionCreated(bytes32 id, uint256 indexed assetId, address indexed seller, uint256 priceInWei, uint256 expiresAt);
    event AuctionSuccessful(bytes32 id, uint256 indexed assetId, address indexed seller, uint256 totalPrice, address indexed winner);
    event AuctionCancelled(bytes32 id, uint256 indexed assetId, address indexed seller);
 ```

**Comment by eordano** [comment]
These events are related to the second LAND auction, and can be removed safely. We include them in the source code for the sake of visibility and transparency when exploring past events.

**Comment by mudgen** [comment]
Cool, thank you.
