### ISSUE TITLE
Facing error while executing order

### ISSUE THREAD

**Issue by Sumair-Aslam** [decentraland/marketplace-contracts#54]
When I execute order in market place contract I got an error "ERC721: operator query for nonexistent token". I don't understand it because I have created the order with same ERC721 contract with same asset id, but while executing It throw me this error.

**Comment by nachomazzara** [comment]
Can you provide code snippets?

**Comment by Sumair-Aslam** [comment]
[SUPER_NFT.zip](https://github.com/decentraland/marketplace-contracts/files/6360998/SUPER_NFT.zip)
This is the NFT file

**Comment by nachomazzara** [comment]
Please, provide the screenshot here. Or send a link to the repo you are working on. I can't download any file

**Comment by Sumair-Aslam** [comment]
![Screenshot (47)](https://user-images.githubusercontent.com/80763643/115839743-65511780-a434-11eb-95a2-b4fff4852da7.png)

**Comment by Sumair-Aslam** [comment]
![Screenshot (48)](https://user-images.githubusercontent.com/80763643/115840274-ee684e80-a434-11eb-83b6-e0298a83d00a.png)

**Comment by nachomazzara** [comment]
Have you minted that NFT token?

**Comment by Sumair-Aslam** [comment]
Yes. Otherwise It can not place order at first

**Comment by Sumair-Aslam** [comment]
Any Suggestions about how to resolve this error?

**Comment by nachomazzara** [comment]
Can you share a github repo or gist with the code of both contracts so I can paste them on remix?

**Comment by nachomazzara** [comment]
Closed by inactivity
